# Configuración básica de Jekyll
title: Ignacio Duarte's Personal Blog
description: Mi blog personal sobre mí, mis ideas y proyectos...
url: "https://ignaciodrd.github.io" # La URL base de tu sitio
baseurl: "/personal_blog_ig/" # El subdirectorio de tu sitio

# Configuración de Markdown
markdown: kramdown
