backend:
  name: github
  repo: ignaciodrd/personal_blog_ig
  branch: main
  
  # Usa el servicio de autenticación oficial de Decap
  base_url: https://api.decapcms.org
  auth_endpoint: auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Artículos del Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }