backend:
  name: github
  repo: ignaciodrd/personal_blog_ig # Ruta a tu repositorio
  branch: main # O la rama principal que estés usando
  
  # --- CORRECCIÓN ---
  # Hemos eliminado las líneas 'base_url' y 'auth_type: github'.
  # Esto permitirá que Decap use el 'auth gateway' por defecto,
  # que es un servicio gratuito que maneja el login con GitHub
  # por nosotros.
  # --- Fin de la corrección ---

media_folder: "assets/images" # Dónde guardar las imágenes
public_folder: "/assets/images" # Cómo acceder a ellas

collections:
  - name: "blog" # ID de la colección
    label: "Artículos del Blog" # Nombre en la UI
    folder: "_posts" # Dónde se guardan los archivos
    create: true # Permitir crear nuevos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato del nombre de archivo
    fields: # Campos para cada artículo
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }

